name: cardano_wallet_sdk
description: Targeting Flutter apps, the Cardano Wallet SDK is a high-level Dart library for managing cryptocurrency accounts & executing transactions on the blockchain.
version: 0.1.0-alpha.12
homepage: https://github.com/reaster/cardano_wallet_sdk
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  # analyzer: ^5.7.0
  blockfrost:
    git:
      url: https://github.com/ArunBabu98/blockfrost
      ref: master
  # blockfrost:
  #   path: ../blockfrost_api
  bip32_ed25519: 0.5.0
  pinenacl: ^0.5.0
  crypto: ^3.0.3
  base_x: ^2.0.0
  built_collection: ^5.1.0
  built_value: ^8.1.0
  cbor: ^5.0.1
  collection: ^1.15.0
  convert: ^3.1.1
  dio: ^5.1.1
  hex: ^0.2.0
  intl: ^0.18.1
  json_annotation: ^4.4.0
  logging: ^1.0.2
  oxidized: ^5.1.0
  quiver: ^3.0.1+1
  typed_data: ^1.3.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_lints: ^2.0.3
  http: ^1.1.0
  json_serializable:
  lints: ^2.0.0
  mockito: ^5.4.2
  test: any
# dependency_overrides:
#   pinenacl:
#     path: ../pinenacl-dart
# bip32_ed25519:
#   path: ../bip32-ed25519-dart
# blockfrost:
# git: git@github.com:reaster/blockfrost_api.git
# path: ../blockfrost_api

flutter:
  assets:
    - assets/bip39/english.txt
