name: cardano_wallet_sdk
description: Cardano Wallet SDK.
version: 0.1.0
author: richard@OutsourceCafe.com
homepage: https://github.com/reaster/cardano_wallet_sdk

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  coingecko_dart: ^0.1.0
  # pointycastle: ^3.0.1
  # base58check: ^2.0.0
  convert: ^3.0.0
  bip32_ed25519: #^0.2.1
    path: ../bip32-ed25519-dart
  blockfrost: #^0.2.1
    path: ../blockfrost_api
  bip39: ^1.0.6
  cryptography: ^2.0.1
  pedantic: ^1.11.0
  oxidized: ^4.2.0

  # bitcoin_bip44: ^0.1.0

dev_dependencies:
  test: any
  build_runner: ^2.0.3
#  pedantic: ^1.11.0
