name: cardano_wallet_sdk
description: Cardano Wallet SDK.
version: 0.1.0-alpha.3
homepage: https://github.com/reaster/cardano_wallet_sdk

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  coingecko_dart: ^0.1.0
  # pointycastle: ^3.0.1
  # base58check: ^2.0.0
  convert: ^3.0.0
  # bip32_ed25519: #^0.2.1
  #   git: git@github.com:ilap/bip32-ed25519-dart.git
  # path: ../bip32-ed25519-dart
  blockfrost:
    ^0.1.23-dev.4
    # git: git@github.com:reaster/blockfrost_api.git
    # path: ../blockfrost_api
  pinenacl: ^0.3.1
  bip39: ^1.0.6
  cryptography: ^2.0.1
  pedantic: ^1.11.0
  oxidized: ^4.2.0
  intl: ^0.17.0
  dio: ^4.0.0
  built_collection: ^5.1.0
  built_value: ^8.1.0
  hex: ^0.2.0
  cbor:
    # ^4.0.2
    path: ../cbor
  quiver: ^3.0.1
  # kms: ^0.4.1 # Key Management Service
  # bitcoin_bip44: ^0.1.0

dev_dependencies:
  test: any
  build_runner: ^2.0.3
  mockito: ^5.0.10
#  pedantic: ^1.11.0
