name: cardano_wallet_sdk_ci

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types:
      - opened
      - ready_for_review

jobs:
  verify_equation_package:
    name: Cardano Wallet SDK package - CI action
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false && github.event.pull_request.merged == false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3

      - name: Installing the dependencies
        run: flutter pub get

      - name: Making sure the package is formatted
        run: flutter format --set-exit-if-changed lib test

      - name: Making sure that there are no analysis warnings or errors
        run: flutter analyze --fatal-infos --fatal-warnings

      - name: Runing unit and widget tests
        run: flutter test --coverage

      - name: Making sure that code coverage is at least 95
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          min_coverage: 65
          
      - name: Uploading coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
